name: mdl_template_blog
version: 0.0.1
description: Material Design Lite 'Blog' Template
#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  logging: any
  logging_handlers: any
  console_log_handler: any

  dice: ^1.7.0
    # path: /Volumes/Daten/DevLocal/DevDart/dice

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - dart_to_js_script_rewriter
