name: mdl_inplace_edit_sample
description: Material Design Lite 'Inplace edit' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: any
  logging_handlers: any
  console_log_handler: any
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  di: ^3.3.0

  uuid: ^0.5.0

  dart_to_js_script_rewriter: ^0.1.0

dev_dependencies:
  test: any

transformers:
  - di
  - dart_to_js_script_rewriter

#  - $dart2js:
#      minify: false
#      sourceMaps: true



