name: mdl_inplace_edit_sample
description: Material Design Lite 'Inplace edit' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  uuid: ^0.5.0

dev_dependencies:

  dart_to_js_script_rewriter: ^0.1.0

  test: any

transformers:
  - dart_to_js_script_rewriter

#  - $dart2js:
#      minify: false
#      sourceMaps: true



