name: mdl_inplace_edit_sample
description: Material Design Lite 'Inplace edit' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    # '>=2.1.0 <3.0.0'
    # git:
    #  url: git@github.com:MikeMitterer/dart-material-design-lite.git
    #  ref: v2.2
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  uuid: ^0.5.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: any



