name: mdl_site
version: 1.19.4
description: Material Design Lite
author: <Mike Mitterer> <office@mikemitterer.at>
homepage: http://www.material-design-lite.pub/

environment:
  sdk: ^1.0.0

dependencies:
  browser: ^0.10.0

  mdl:
    # '>=2.1.0 <3.0.0'
    git:
      url: git@github.com:MikeMitterer/dart-material-design-lite.git
    #  ref: v2.2
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  prettify: ^0.1.0

dev_dependencies:
  test: any
  grinder: any
  mdl_grinder:
    git: https://github.com/MikeMitterer/dart-mdl-grinder
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialGrinder

transformers:
#  - di

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]
      minify: false
      sourceMaps: true
