name: mdl_badge_sample
description: Material Design Lite 'badge' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: ^0.15.0
  args: any
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

dev_dependencies:

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - dart_to_js_script_rewriter

#  - $dart2js:
#      commandLineOptions: [--enable-experimental-mirrors]
#      minify: false
#      sourceMaps: true