name: mdl_chartjs_sample
description: Material Design Lite 'Shows ChartJS in action' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: ^0.14.0
  args: any
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  dice: ^1.7.0
    # path: /Volumes/Daten/DevLocal/DevDart/dice

  chartjs: any

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - dart_to_js_script_rewriter
  
#  - $dart2js:
#      minify: false
#      sourceMaps: true



