name: mdl_template_sticky_footer
version: 0.0.1
description: Material Design Lite 'Sticky footer' Template
#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mdl:
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

dev_dependencies:

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - dart_to_js_script_rewriter
