name: mdl_styleguide
description: MDL Sample 'styleguide' - Material Design
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-mdl

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  intl: ^0.15.0
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    # '>=2.1.0 <3.0.0'
    git:
      url: git@github.com:MikeMitterer/dart-material-design-lite.git
    #  ref: v2.2
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  prettify: ^0.1.0

dev_dependencies:

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - dart_to_js_script_rewriter

#  - $dart2js:
#      commandLineOptions: [--enable-experimental-mirrors]
#      minify: false
#      sourceMaps: true



